theme: jekyll-theme-minimal
title: dalecousins83 - De-central
description: Thoughts on decentralisation
url: https://github.com/dalecousins83/dalecousins83.github.io
baseurl: dalecousins83.github.io
remote_theme: manid2/lone-wolf-theme
plugins:
  - jekyll-remote-theme
index.md
